### ISSUE TITLE
Task 007 : I#3 - Assistant's general data.

### ISSUE THREAD

**Issue by laurolmer** [laurolmer/Acme-L3-D02#15]
7)	The system must handle assistant dashboards with the following data: total number of tutorials regarding theory or hands-on courses; average, deviation, minimum, and maximum time of his or her sessions; average, deviation, minimum, and maximum time of his or her tutorials.

**Comment by Albertoperleo** [comment]
Todo aparentemente ok en la pull-request. Cierro el issue.
