### ISSUE TITLE
Task 004 : I#1 - Create a Lecturer entity.

### ISSUE THREAD

**Issue by laurolmer** [laurolmer/Acme-L3-D02#19]
4)	There is a new project-specific role called lecturer, which has the following profile data: alma mater (not blank, shorter than 76 characters), a résumé (not blank, shorter than 101 characters), list of qualifications (not blank, shorter than 101 characters), and an optional link with further information.

**Comment by Albertoperleo** [comment]
@laurolmer @AlvaroHR12 @Danguepre @ivasansan1 preguntar al tutor acerca del atributo list of qualifications ya que podría llegar a interpretarse como una lista en lugar de un string. Esta duda viene porque en las restricciones a tener en cuenta dice _'shorter than 101 characters'_.
