### ISSUE TITLE
Task 008 : I#1 - Generate sample data.

### ISSUE THREAD

**Issue by laurolmer** [laurolmer/Acme-L3-D02#23]
8)	[MANDATORY] Produce assorted sample data to test your application informally. The data must include two lecturer accounts with credentials “lecturer1/lecturer1” and “lecturer2/lecturer2”.

**Comment by Albertoperleo** [comment]
Hay errores en los formatos de los TIMESTAMPS que hay que corregir de `yyyy/MM/dd HH:mm:ss` a `yyyy/MM/dd HH:mm`.
