### ISSUE TITLE
Task 005 : I#4 - Create a Practicum entity.

### ISSUE THREAD

**Issue by laurolmer** [laurolmer/Acme-L3-D02#34]
5) [MANDATORY] A practicum helps put hands-on courses into practice in the context of a real company. The system must store the following data about them: a code (pattern “[A-Z]{1,3}[0-9][0-9]{3}”, not blank, unique), a title (not blank, shorter than 76 characters), an abstract (not blank, shorter than 101 characters), some goals (not blank, shorter than 101 characters), and an estimated total time (in hours, computed from the corresponding sessions plus/minus 10%)

**Comment by ivasansan1** [comment]
Tiene una relación OneToMany con courses?
Tiene una relación  OneToOne con company?
